
  build-docker-image-tag:
    image: plugins/docker
    insecure: true
    registry: {{ registry_domain }}
    repo: {{ registry_url }}
    file: Dockerfile
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]

  prebuild-docker-static-image:
    image: python:3.6-alpine3.7
    commands:
      - bash scripts/run-collectstatic.sh
    when:
      event: [tag]
      status: [success]

  build-docker-static-image-tag:
    image: plugins/docker
    insecure: true
    registry: {{ registry_domain }}
    repo: {{ registry_url }}_static
    dockerfile: Dockerfile.nginx
    auto_tag: true
    secrets: [DOCKER_USERNAME, DOCKER_PASSWORD]
    when:
      event: [tag]
      status: [success]
